inherit_from:
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
    - config.ru
    - Gemfile
    - Rakefile

Metrics/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false
